pattern =  ['ALL new 𝒄hapters 𝒐n nov(𝒆)lbin(.)com', 
            'Aall 𝒏𝒆west ch𝒂pt𝒆rs on n.o./v𝒆l𝒃i/n/(.)c𝒐m',
            'AlLll new 𝒄hapters 𝒐n nov(𝒆)lbin(.)com', 
            'Alll 𝒏𝒆west ch𝒂pt𝒆rs on no./v𝒆l𝒃i/n/(.)c𝒐m',
            'Alll 𝒏𝒆west ch𝒂pt𝒆rs on no./v𝒆l𝒃i/n/(.)c𝒐m',
            'Alll 𝒍𝒂test nov𝒆l𝒔 on novelb𝒊n/(.)c𝒐m',
            'All 𝒏𝒆west ch𝒂pt𝒆rs on nov𝒆l𝒃in(.)c𝒐m',
            'ALL new 𝒄hapters 𝒐n n𝒐v(𝒆)lbin(.)com',
            '𝒂ll new st𝒐ries at n0ve/lbi/𝒏(.)c𝒐m',
            'All ɴᴏᴠᴇʟ full.com',
            'All-Novel--Full. C0 m',
            'AllNovelFull.Com',
            'Check new 𝒏ovel ch𝒂pters at nov𝒆l𝒃in(.)com',
            'CH𝒆Ck for 𝒏ew st𝒐ries on no/v/el/bin(.)c0m' ,
            'Ch𝒆ck out l𝒂t𝒆st 𝒏𝒐v𝒆l𝒔 on nov𝒆lbin(.)c𝒐m',
            'Checkk new 𝒏ovel ch𝒂pters at nov𝒆lbin(.)com',
            'Ch𝒆êck out l𝒂t𝒆st 𝒏𝒐v𝒆l𝒔 on nov𝒆l/bin(.)c𝒐m',
            'Ch𝒆eck out l𝒂t𝒆st 𝒏𝒐v𝒆l𝒔 on nov𝒆l/bin(.)c𝒐m',
            'Diiscover new 𝒔tories at n𝒐ve/lbin(.)c/o𝒎', 
            'Diisscover n𝒆w chapt𝒆rs 𝒐n n0𝒗e(l)bi𝒏(.)com',
            'DiiScôver 𝒏𝒆w stori𝒆s on no/𝒗/e()/lbin(.)com',
            'DiiScover 𝒏𝒆w stori𝒆s on no/𝒗/e/lbin(.)com',
            'DiisCoover 𝒖pdated novels on n(o)v./e/lbin(.)co𝒎',
            'Discover new 𝒔tories at n𝒐velbin(.)c/o𝒎', 
            'Discover 𝒏ew chapters at novelbi𝒏(.)co𝒎',
            'DiScover 𝒏𝒆w stori𝒆s on no𝒗/e/lbin(.)com', 
            'DissCover 𝒖pdated novels on n(o)v/e/lbin(.)co𝒎',
            'DissCoover 𝒖pdated novels on n(o)v.e/lbin(.)co𝒎',
            'Do you want to read more chapters ? Come to Panda-novel,com',
            'Exxploore 𝒖ptod𝒂te stories at no𝒗el/bin(.)c𝒐m', 
            'Expploore 𝒖ptod𝒂te stories at no/𝒗el/bin(.)c𝒐m',
            'Explore new 𝒏ovels on novelbi𝒏(.)com',
            'Expplôre 𝒖ptod𝒂te stories at no/𝒗el//bin(.)c𝒐m',
            'F0lloww new 𝒄hapters at nov/(e)l/bin/(.)com', 
            'FOlloww 𝒏ewest stories at n𝒐(v)el/bin(.)com',
            'Foolloow 𝒏ew stories at n𝒐/v(e)lbin(.)com',
            'Find new 𝒔tories on novelbin(.)com', 
            'Find upd𝒂ted 𝒏ovels on n𝒐velbin(.)co/m', 
            'Finnd new 𝒔tories on nove(l)bin(.)com',
            'FiNd 𝒖pd𝒂tes on n(𝒐)/v𝒆l𝒃𝒊n(.)c𝒐m',
            'Fi𝒏d 𝒏ew upd𝒂t𝒆s on novel𝒃in(.)com', 
            'Fi𝒏dd 𝒏ew upd𝒂t𝒆s on nove/l𝒃in(.)com',
            'Findd new 𝒔tories on nov/e(l)bin(.)com',
            'Fị𝒏dd 𝒏ew upd𝒂t𝒆s on n(o)v/e/l𝒃in(.)com',
            'Fi𝒏ndd 𝒏ew upd𝒂t𝒆s on n/ov/e/l𝒃in(.)com',
            'Finndd the new𝒆st 𝒏ovels on n/𝒐/velbin(.)com',
            'Finnd 𝒏ew chapters on n𝒐ve/lbi𝒏(.)com',
            'Fi𝒏nd 𝒏ew upd𝒂t𝒆s on n/ove/l𝒃in(.)com',
            'Findd the new𝒆st 𝒏ovels on n/𝒐velbin(.)com',
            'Fiind upd𝒂ted 𝒏ovels on n𝒐/v/elbin(.)co/m',
            'Folll0w current novÊls on n/o/v/3l/b((in).(co/m)',
            'FOlloow 𝒏ewest stories at n𝒐(v)el/bi/n(.)com',
            'Fôll0w current novÊls on n/o/(v)/3l/b((in).(co/m)',
            'Foll0w current novÊls on nov/3lb((in).(co/m)', 
            'Foll0w current novÊls on n𝒐v/3lb((in).(co/m)', 
            'Foll0ww current novÊls on nov/3l/b((in).(co/m)',
            'Fôllôw 𝒏ew stories at n𝒐/v(e)lb/in(.)com',
            'Foll00w current novÊls on n/ov/3l/b((in).(co/m)' ,
            'Follow new 𝒄hapters at novelbin(.)com', 
            'Follow the latest novels 𝒐𝒏 n𝒐velbin(.)com', 
            'Follow the latest novels 𝒐𝒏 n𝒐/velbin(.)com',
            'Follow the latest novels 𝒐𝒏 n𝒐vel𝒃in(.)com', 
            'Foll𝑜w current novℯls on nov𝒆lb((in).(com)',
            'Free Web Novel',
            'Get the l𝒂test 𝒏𝒐vels on novelbin(.)c/om', 
            'Get your 𝒇avorite 𝒏ovels at novelb𝒊n(.)com',
            'Gét latest 𝒏ovel ch𝒂pters on n𝒐v(e)lbj/n(.)c/𝒐m',
            'Get your 𝒇avorit𝒆 𝒏ovels at novelb𝒊n(.)com', 
            'Geett your 𝒇avorite 𝒏ovels at no/ve/lb𝒊n(.)com',
            'Geet latest 𝒏ovel ch𝒂pters on n𝒐velbj/n(.)c/𝒐m',
            'Geett the l𝒂test 𝒏𝒐vels on no/v/elbin(.)c/om',
            'Geet your 𝒇avorite 𝒏ovels at no/velb𝒊n(.)com',
            'Gett the l𝒂test 𝒏𝒐vels on nov/elbin(.)c/om',
            'Gett your 𝒇avorite 𝒏ovels at no/v/e/lb𝒊n(.)com',
            'Gẹtt the l𝒂test 𝒏𝒐v𝒆ls at 𝒏.o/(v)/e/l/bi𝒏(.)co𝒎',
            'GEtt the l𝒂test 𝒏𝒐v𝒆ls at 𝒏.o/(v)/elbi𝒏(.)co𝒎',
            'Gẹtt the l𝒂test 𝒏𝒐v𝒆ls at 𝒏.o/(v)/e/l/bi𝒏(.)co𝒎'
            'Gett your 𝒇avorite 𝒏ovels at no/v/e/lb𝒊n(.)com',
            'Gêtt the latest ch𝒂pters on n𝒐/velbin(.)com', 
            'I think you should take a look at',
            'L𝒂Test nov𝒆ls on (n)𝒐velbi𝒏(.)co𝒎',
            'L𝒂aTest nov𝒆ls on (n)𝒐velbi/𝒏(.)co𝒎',
            'L𝒂test nov𝒆ls on n𝒐velbi𝒏(.)co𝒎',
            '(MT Novel. Com)',
            'Ne/w novel chapt𝒆rs are published on no/vel(/b)in(.)co/m',
            'Ne/w novel chapt𝒆rs are published on no/vel(/bin(.)co/m', 
            'New n0vel chapters are published on n0ve(l)bi(n.)co/m',
            'n𝒆w chapt𝒆rs 𝒐n n0𝒗e(l)bi𝒏(.)com',
            'Nnew n0vel chapters are published on n0v/e(lb)i(n.)co/m',
            'Nnêw n0vel chapters are published on n0v/e/(lb)i(n.)co/m',
            'New n𝙤vel chapters are published on', 
            'Nêw 𝒄hapters will be fully updated at nov(𝒆)l/bin(.)com', 
            'nÊw st𝒐ries at n𝒐/vel/b/i/n(.)co𝒎',
            'Nêww 𝒄hapters will be fully updated at (n)ov(𝒆)l/bin(.)com',
            '𝒩ewW 𝒏ovels upd𝒂tes on nov/𝒆l/b(i)𝒏(.)com',
            'N𝒆/w novel chapt𝒆rs are published on n𝒐/vel(/bin(.)co/m',
            'pan da-nov el ,c`o`m',
            'Pa nda\nNovel',
            'ραΠdαsΝοvel.cοm'
            'Reading on All no vel full. com ,Please!',
            'Read on www.Allno vel full. com ,Please!',
            'Read lat𝙚st chapters at nov(𝒆)lbin.com Only',
            'Rêađ lat𝙚St chapt𝒆r at nô(v)(𝒆)l/bin/.c/o/m Only',
            'RreAd lat𝙚St chapters at nô(v)e/l/bin/.c/o/m Only',
            'Reead latest 𝒏ov𝒆ls at n𝒐v/el/bi𝒏(.)com',
            'RE𝒂d updated st𝒐ries at n/𝒐vel/bin(.)com',
            'RêAd lat𝙚St chapters at nô(v)e(l)bin/.c/o/m Only',
            'Reêad latest 𝒏ov𝒆ls at n𝒐𝒐v/e/l/bi𝒏(.)com',
            'RE𝒂ad updated st𝒐ries at n/𝒐/vel/bin(.)com',
            'RêAd lat𝙚St chapters at nô(v)e(l)bin/.c/o/m Only',
            'RE𝒂ad updated st𝒐ries at n/𝒐/vel/bin(.)com',
            'Re𝒂𝒂d the latest stories 𝒐n nov𝒆lbin(.)com',
            'Reêad latest 𝒏ov𝒆ls at n𝒐v/e/l/bi𝒏(.)com',
            '𝑅êạd new chapt𝒆rs on no/v/e/l𝒃in(.)com',
            'Rêađ lat𝒆st ch𝒂pters on n𝒐/v/𝒆/l(b)i𝒏(.)c𝒐m',
            'Read more, visit: MtNovel.com ',
            'R𝒆ead lat𝒆st ch𝒂pters on n𝒐/v𝒆l(b)i𝒏(.)c𝒐m',
            'R𝒆ead lat𝒆st ch𝒂pters on n𝒐/v𝒆l(b)i𝒏(.)c𝒐m',
            'The latest_epi_sodes are on_the ʟɪʙʀᴇᴀᴅ.ᴄᴏᴍ. website.',
            'T/his chapter is updat𝓮d by nov(ê(l)biin.co/m', 
            'T/his chapter is updat𝓮d by nov(ê(l)𝒃in.co/m',
            'Th/e most uptodat𝓮 n𝒐vels are published on n0velbj)n(.)co/m' ,
            'Th.ê most uptodat𝓮 n𝒐vels are published on n(0)velbj)n(.)co/m',
            'Thê sourc𝗲 of this content n/o/v/(𝒆l)bi((n))',
            'T0p 𝒏𝒐v𝒆l updates on n(o)v𝒆lbin(.)com',
            'T0pp 𝒏𝒐v𝒆l updates on n/(o)v𝒆lbin(.)com',
            'Tôp 𝒏𝒐v𝒆l updates on n/(o)/v/𝒆lb/in(.)com',
            'T0ppp 𝒏𝒐v𝒆l updates on n/(o)v/𝒆lbin(.)com',
            'The sourc𝗲 of this content nov(𝒆l)bi((n))', 
            'THee sourc𝗲 of this content n/o/v/(𝒆l)bi((n))',
            'Thee sourc𝗲 of this content no/v/(𝒆l)bi((n))',
            'Thi/s chapter is updat𝓮d by nov(e)(l)biin.co/m', 
            'This chapter is updat𝓮d by nov(e)(l)biin.com', 
            'ᴜᴘᴅᴀᴛᴇ ꜰʀᴏᴍ ꜰʀᴇᴇᴡ(ᴇʙɴᴏ)ᴠᴇʟ. ᴄᴏᴍ.',
            'UpTodated 𝒏ov𝒆ls on 𝒏ov𝒆l()bin(.)c𝒐m',
            'UpTodated 𝒏ov𝒆ls on 𝒏ov𝒆l()bin(.)c𝒐m',
            'Upttodated from n(0)/v𝒆lbIn/.(co/m',
            'UppTodat𝒆d fr𝒐m nô/v/e/l/b(i)n.c(o)/m',
            'Updated from nov𝒆lbIn.(c)om', 
            'ÚpTodated 𝒏ov𝒆ls on 𝒏o(v)𝒆l()bin(.)c𝒐m',
            'Upstodatee from n(0)/v𝒆/lbIn/.(co/m',
            'UppTodat𝒆d fr𝒐m nô/v/e/lb(i)n.c(o)/m',
            'Updat𝒆d fr𝒐m nov𝒆lb(i)n.c(o)m',
            'Updat𝒆d fr𝒐m n0v3lb(i)n.c(o)/m', 
            'Upd𝒂ted chapters 𝒐n n𝒐velbin(.)com', 
            'Visit no(v)eLb(i)n.𝘤𝑜𝓂 for the best novel reading experience', 
            'Visitt nov𝒆lbin(.)c𝒐/m for the l𝒂test updates',
            'ViiSiit n𝒐velb𝒊/n(.)c/(𝒐)m for l𝒂test 𝒏𝒐vels',
            'VIssịT n0(v)eL/b(i)(n).𝘤𝑜𝓂 for the best novel reading experience',
            'ViiSit no(v)3lb!n(.)c𝒐m for new 𝒏ov𝒆l𝒔',
            'ViiSit no(v)3lb!n(.)c𝒐m for new 𝒏ov𝒆l𝒔',
            'ViiSit n𝒐velb𝒊n(.)c/(𝒐)m for l𝒂test 𝒏𝒐vels',
            'Visit nov3lb!n(.)c𝒐m for new 𝒏ov𝒆l𝒔',
            'Visjt n𝒐velbin(.)c𝒐m for new updates',
            'VịSit no(v)3lb/!n(.)c𝒐m for new 𝒏ov𝒆l𝒔',
            'Visit nov𝒆lbin(.)c𝒐m for the l𝒂test updates', 
            'Visit nov𝒆lbin(.)c𝒐m for updates', 
            'Visjt n𝒐velbin(.)c𝒐m for new updates',
            'Vissit n𝒐velbin(.)c𝒐m for 𝒏ew 𝒏ovels',
            'Vissit novelbin(.)c.𝒐m for updates',
            'VIssiT n0(v)eL/b(i)(n).𝘤𝑜𝓂 for the best novel reading experience',
            'Y0ur favorite 𝒏ovels at novelbin(.)com',
            'Yoouur favorite 𝒏ovels at n/ovel/bin(.)com',
            'Yôur favorite 𝒏ovels at n/o(v)el/bin(.)com',
            'Yôur favorite 𝒏ovels at n/𝒐(v)el/bin(.)com',
            'Yôur f𝒂vorite stories on 𝒏/o/(v)𝒆/lb𝒊n(.)c𝒐m',
            'Yoour f𝒂vorite stories on 𝒏/o/(v)𝒆lb𝒊n(.)c𝒐m',
            '𝑅ead new chapt𝒆rs on novel𝒃in(.)com',
            '𝑅ead latest ch𝒂pters at n/𝒐velbi𝒏(.)co/m', 
            '𝑅eead new chapt𝒆rs on nove/l𝒃in(.)com',
            '𝑅read latest ch𝒂pters at n/𝒐v(e)lbi𝒏(.)co/m',
            '𝒂ll new st𝒐ries at novelbi𝒏(.)c𝒐m', 
            '𝒂ll new st𝒐ries at nove/lbi/𝒏(.)c𝒐m',
            '𝒩eW 𝒏ovels upd𝒂tes on nov𝒆l/b(i)𝒏(.)com',
            '𝒩Eew st𝒐ries at n𝒐/vel/bi/n(.)co𝒎',
            '𝒩eew updates 𝒂t n𝒐vel/bi𝒏(.)com',
            '—— Rêađ lat𝒆st ch𝒂pters on n𝒐/v/𝒆/l(b)i𝒏(.)c𝒐m',
            'nove(l)bi(n.)com',
            '@@novelbin@@',
            'ρꪖꪕᦔꪖꪕꪫꪣꫀꪶ',
            'ɴ[0)ᴠᴇʟ ',
            '-ɴ(0ᴠᴇ)ʟ',
            'ρꪖnᦔa (nꪫꪣ)ꫀꪶ ',
            'Enhance your reading experience by removing ads for as low as $1!',
            'REMOVE ADS FROM $1',]

replacement = ""
